--- 
title: "LOL Tournament Data Analysis"
author: "Tongni Chem, Tao Yu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

In recent years, popularity of e-sports has dramatically increased all over the world. There are official tournaments hold for different games, and they have also gradually entered some mainstream large stages, such as the Asian Games. As fans and also players of video games, we would like to choose e-sports as topic for this project.


The game we would like to investigate is League of Legends (LOL), a worldwide popular Multiplayer Online Battle Arena (MOBA) game. Riot Game, the company that develops LOL, holds official tournaments each year. Our project will investigate on data from these official tournaments.


There are totally 12 divisions of leagues from 12 different countries worldwide. Among these 12 divisions, there are four major divisions, in which the competitive levels are the highest, as well as the degree of professionalism and the arrangements of tournaments are the most standardized and procedural.


The four major divisions are: 

LPL, China; 

LCK, South Korea; 

LCS, North America; 

LEC, Europe.


There are four major seasons in each year: 

Spring Season; 

Mid-Season Invitational (MSI); 

Summer Season; 

World Championship.


Spring and summer season tournaments are hold domestically in each division; MSI and World are international tournaments where eligible teams from each division gather together and compete each other to get the final world champion.


Our project will firstly focus on the relationship between different factors in the game, for example relationship between total kills and total gold, will higher total damage bring higher wining rate, etc.. 

After that, we will also compare and contrast the data from different seasons and from different four major divisions, for example, since we are fans of LPL division, we would like to see how LPL teams stat change over different seasons, or how KD (kill-to-death ratio) change in different divisions. 

